### ISSUE TITLE
Image quality - check orientation

### ISSUE THREAD

**Issue by jbest** [TORCH-TCN/torch_hub#73]
Make sure each image is in portrait orientation.

**Comment by jbest** [comment]
If an image is not in portrait orientation processing should stop (we don't want to generate images, upload etc). Orientation can be fixed on the fly but we'll wait to do that for a later time if we choose to do so.

**Comment by antoniocorreia** [comment]
@jbest I remember you saying that there's an easy way of checking if the image is not in portrait orientation can you send us here so we can double-check this?

Also, I think we can start to think/discuss if you would like us to proceed with some sort of mechanism to automatically fix this since we were discussing the possibility of getting the barcode and numbers below to check that, what are your thoughts?

**Comment by jbest** [comment]
@antoniocorreia I think something along these lines should work to check orientation:
```
from PIL import Image

def is_portrait(image_path=None):
    with Image.open(image_path) as im:
        width, height = im.size
        if height > width:
            return True
        else:
            return False
```

**Comment by jbest** [comment]
@antoniocorreia Regarding automatically fixing orientation, I think this should be a pretty low priority at this point because 1) determining the top vs. bottom of a specimen will vary across different herbaria. At BRIT, the barcodes are at the bottom and the scale bar and color bar are at the top. Other herbaria have this reversed. Other methods would also be only partially reliable. I think it's doable, but would require a lot of effort. 2) I'm not sure I want to automatically fix orientation because it's a sign of a problem that should be fixed earlier in the process (before upload). 3) but, if we do eventually implement a way to fix orientation after upload, the problem images from any one herbarium will probably all be rotated the same way (-90° or 90°) so we could provide a UI that shows one image and asks the user to determine which way it needs to rotate, then apply that to all non-portrait images.

**Comment by antoniocorreia** [comment]
@jbest ok, thank you! So we're thinking in
1. Add the `is_portrait` function to the specimen _entity/utilities_ script, this way we can make use of that both on the website or any workflow script that may reference this
2. Develop a web control so the users can view and rotate an image when necessary (after the upload as you said)

**Comment by jbest** [comment]
@antoniocorreia sounds good about #1. Let's not plan on implementing #2 (UI for image rotation) until I've had a chance to  discuss more with the team.
