### ISSUE TITLE
Link Folder to Workflow

### ISSUE THREAD

**Issue by GorkiGonzalez** [TORCH-TCN/torch_hub#8]

**Comment by jbest** [comment]
I'm not sure this is relevant to this phase, maybe should be in Phase 2? That's when SFTP will be implemented and SFTP folders will be used as an option for queuing  images.

**Comment by antoniocorreia** [comment]
solved on the [P2 Milestone 2 - SFTP & workflow](https://github.com/TORCH-TCN/torch_hub/milestone/7) - probably will be revisited later
